CREATE TABLE ex_table (BOARD_NUM NUMBER(19, 6) NOT NULL);

CREATE SEQUENCE ex_seq
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 100
NOCYCLE
NOCACHE;

INSERT INTO ex_table(board_num) VALUES(EX_SEQ.NEXTVAL);
INSERT INTO ex_table(board_num) VALUES(EX_SEQ.NEXTVAL);
INSERT INTO ex_table(board_num) VALUES(EX_SEQ.NEXTVAL);

SELECT *
FROM ex_table;

SELECT ex_seq.CURRVAL
FROM dual;

ALTER SEQUENCE ex_seq
INCREMENT BY 2
MINVALUE 2
MAXVALUE 10000
CYCLE
NOCACHE;

DROP SEQUENCE ex_seq;

-----

CREATE OR REPLACE SYNONYM history
FOR HR.JOB_HISTORY;

SELECT *
FROM history;

SELECT *
FROM user_synonyms;

SELECT *
FROM all_synonyms;

DROP SYNONYM history;